-- MySQL Script generated by MySQL Workbench
-- 08/08/17 09:32:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema unstructured
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `unstructured` ;

-- -----------------------------------------------------
-- Schema unstructured
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unstructured` DEFAULT CHARACTER SET utf8 ;
USE `unstructured` ;

-- -----------------------------------------------------
-- Table `unstructured`.`document_sources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unstructured`.`document_sources` ;

CREATE TABLE IF NOT EXISTS `unstructured`.`document_sources` (
  `ds_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `type` VARCHAR(20) NULL,
  `status` INT NULL DEFAULT 1,
  `refresh_mins` INT NULL DEFAULT 90,
  `last_scanned` DATETIME NULL,
  PRIMARY KEY (`ds_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unstructured`.`documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unstructured`.`documents` ;

CREATE TABLE IF NOT EXISTS `unstructured`.`documents` (
  `doc_id` INT NOT NULL AUTO_INCREMENT,
  `ds_id` INT NOT NULL,
  `orig_id` VARCHAR(99) NOT NULL,
  `content` LONGTEXT NULL,
  `length` INT NULL,
  `words` INT NULL,
  `doc_date` DATETIME NULL,
  `last_processed` DATETIME NULL,
  `last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`doc_id`, `ds_id`),
  INDEX `doc_date_idx` (`doc_date` ASC),
  INDEX `orig_id_idx` (`orig_id` ASC),
  INDEX `last_updated_idx` (`last_updated` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unstructured`.`ca_sentiment_documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unstructured`.`ca_sentiment_documents` ;

CREATE TABLE IF NOT EXISTS `unstructured`.`ca_sentiment_documents` (
  `doc_id` INT NOT NULL,
  `tone` VARCHAR(20) NOT NULL,
  `tone_positive_score` DECIMAL(10,5) NULL,
  `tone_positive_distribution` DECIMAL(10,5) NULL,
  `tone_negative_score` DECIMAL(10,5) NULL,
  `tone_negative_distribution` DECIMAL(10,5) NULL,
  `subjectivity` VARCHAR(20) NULL,
  `subjectivity_score` DECIMAL(10,5) NULL,
  `subjectivity_distribution` DECIMAL(10,5) NULL,
  INDEX `tone_idx` (`tone` ASC),
  PRIMARY KEY (`doc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unstructured`.`ca_sentiment_sentences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unstructured`.`ca_sentiment_sentences` ;

CREATE TABLE IF NOT EXISTS `unstructured`.`ca_sentiment_sentences` (
  `doc_id` INT NOT NULL,
  `sentence_begin` INT NOT NULL,
  `sentence_end` INT NULL,
  `sentence` VARCHAR(2000) NULL,
  `tone` VARCHAR(20) NOT NULL,
  `tone_positive_score` DECIMAL(10,5) NULL,
  `tone_negative_score` DECIMAL(10,5) NULL,
  `subjectivity` VARCHAR(20) NULL,
  `subjectivity_score` DECIMAL(10,5) NULL,
  INDEX `tone_idx` (`tone` ASC),
  PRIMARY KEY (`doc_id`, `sentence_begin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unstructured`.`ca_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unstructured`.`ca_categories` ;

CREATE TABLE IF NOT EXISTS `unstructured`.`ca_categories` (
  `doc_id` INT NOT NULL,
  `kb_id` VARCHAR(20) NOT NULL,
  `category_id` VARCHAR(20) NOT NULL,
  `relevancy_score` INT NULL,
  `weight` DECIMAL(10,5) NULL,
  `rejected` INT NULL DEFAULT 0,
  `category` VARCHAR(100) NULL,
  INDEX `kb_category_idx` (`kb_id` ASC, `category_id` ASC),
  PRIMARY KEY (`doc_id`, `kb_id`, `category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unstructured`.`ca_concepts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unstructured`.`ca_concepts` ;

CREATE TABLE IF NOT EXISTS `unstructured`.`ca_concepts` (
  `doc_id` INT NOT NULL,
  `type` INT NOT NULL,
  `concept` VARCHAR(100) NOT NULL,
  `frequency` INT NULL,
  `relevancy` INT NULL,
  INDEX `type_idx` (`type` ASC),
  PRIMARY KEY (`doc_id`, `type`, `concept`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unstructured`.`ca_terms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unstructured`.`ca_terms` ;

CREATE TABLE IF NOT EXISTS `unstructured`.`ca_terms` (
  `doc_id` INT NOT NULL,
  `cartridge` VARCHAR(20) NOT NULL,
  `term_id` VARCHAR(100) NOT NULL,
  `confidence_score` DECIMAL(10,5) NULL,
  `relevancy_score` DECIMAL(10,5) NULL,
  `frequency` INT NULL,
  `subjectivity` VARCHAR(20) NULL,
  `subjectivity_confidence_score` DECIMAL(10,5) NULL,
  `subjectivity_score` DECIMAL(10,5) NULL,
  `subjectivity_distribution` DECIMAL(10,5) NULL,
  `tone` VARCHAR(20) NOT NULL,
  `tone_confidence_score` DECIMAL(10,5) NULL,
  `tone_positive_score` DECIMAL(10,5) NULL,
  `tone_positive_distribution` DECIMAL(10,5) NULL,
  `tone_negative_score` DECIMAL(10,5) NULL,
  `tone_negative_distribution` DECIMAL(10,5) NULL,
  `main_term` VARCHAR(100) NULL,
  PRIMARY KEY (`doc_id`, `cartridge`, `term_id`),
  INDEX `tone_idx` (`tone` ASC),
  INDEX `main_term_idx` (`main_term` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unstructured`.`document_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unstructured`.`document_meta` ;

CREATE TABLE IF NOT EXISTS `unstructured`.`document_meta` (
  `doc_id` INT NOT NULL AUTO_INCREMENT,
  `meta_attribute1` VARCHAR(99) NULL,
  PRIMARY KEY (`doc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unstructured`.`ca_term_subterms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unstructured`.`ca_term_subterms` ;

CREATE TABLE IF NOT EXISTS `unstructured`.`ca_term_subterms` (
  `doc_id` INT NOT NULL,
  `cartridge` VARCHAR(20) NOT NULL,
  `term_id` VARCHAR(100) NOT NULL,
  `position` INT NOT NULL,
  `length` INT NULL,
  `subjectivity` VARCHAR(20) NULL,
  `subjectivity_confidence_score` DECIMAL(10,5) NULL,
  `subjectivity_score` DECIMAL(10,5) NULL,
  `tone` VARCHAR(20) NOT NULL,
  `tone_confidence_score` DECIMAL(10,5) NULL,
  `tone_positive_score` DECIMAL(10,5) NULL,
  `tone_negative_score` DECIMAL(10,5) NULL,
  `sentence_begin` INT NULL,
  `sentence_end` INT NULL,
  `sentence` VARCHAR(2000) NULL,
  `sub_term` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`doc_id`, `cartridge`, `term_id`, `position`),
  INDEX `tone_idx` (`tone` ASC),
  INDEX `sub_term_idx` (`sub_term` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unstructured`.`ca_geo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unstructured`.`ca_geo` ;

CREATE TABLE IF NOT EXISTS `unstructured`.`ca_geo` (
  `doc_id` INT NOT NULL,
  `cartridge` VARCHAR(20) NOT NULL,
  `term_id` VARCHAR(99) NOT NULL,
  `geo_type` VARCHAR(20) NOT NULL,
  `confidence_score` DECIMAL(10,5) NULL,
  `relevancy_score` DECIMAL(10,5) NULL,
  `frequency` INT NULL,
  `subjectivity` VARCHAR(20) NULL,
  `subjectivity_confidence_score` DECIMAL(10,5) NULL,
  `subjectivity_score` DECIMAL(10,5) NULL,
  `subjectivity_distribution` DECIMAL(10,5) NULL,
  `tone` VARCHAR(20) NOT NULL,
  `tone_confidence_score` DECIMAL(10,5) NULL,
  `tone_positive_score` DECIMAL(10,5) NULL,
  `tone_positive_distribution` DECIMAL(10,5) NULL,
  `tone_negative_score` DECIMAL(10,5) NULL,
  `tone_negative_distribution` DECIMAL(10,5) NULL,
  `geo_term` VARCHAR(100) NULL,
  PRIMARY KEY (`doc_id`, `cartridge`, `term_id`, `geo_type`),
  INDEX `tone_idx` (`tone` ASC),
  INDEX `geo_term_idx` (`geo_term` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unstructured`.`document_source_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unstructured`.`document_source_meta` ;

CREATE TABLE IF NOT EXISTS `unstructured`.`document_source_meta` (
  `ds_id` INT NOT NULL,
  `meta_attribute1` VARCHAR(45) NULL,
  PRIMARY KEY (`ds_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unstructured`.`ca_concept_subterms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unstructured`.`ca_concept_subterms` ;

CREATE TABLE IF NOT EXISTS `unstructured`.`ca_concept_subterms` (
  `doc_id` INT NOT NULL,
  `type` INT NOT NULL,
  `concept` VARCHAR(100) NOT NULL,
  `position` INT NOT NULL,
  `length` INT NULL,
  `text_part` VARCHAR(20) NULL,
  `sub_term` VARCHAR(100) NULL,
  PRIMARY KEY (`doc_id`, `type`, `concept`, `position`),
  INDEX `sub_term_idx` (`sub_term` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unstructured`.`ca_summaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unstructured`.`ca_summaries` ;

CREATE TABLE IF NOT EXISTS `unstructured`.`ca_summaries` (
  `doc_id` INT NOT NULL,
  `summary` TEXT NULL,
  PRIMARY KEY (`doc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unstructured`.`terms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unstructured`.`terms` ;

CREATE TABLE IF NOT EXISTS `unstructured`.`terms` (
  `cartridge` VARCHAR(20) NOT NULL,
  `term_id` VARCHAR(45) NOT NULL,
  `parent_term_id` VARCHAR(45) NULL,
  `main_term` VARCHAR(100) NULL,
  `type` VARCHAR(100) NULL,
  `de` VARCHAR(100) NULL,
  `en` VARCHAR(100) NULL,
  `es` VARCHAR(100) NULL,
  `fr` VARCHAR(100) NULL,
  `un` VARCHAR(100) NULL,
  `iso_3166_1` VARCHAR(2) NULL,
  `iso_3166_2` VARCHAR(20) NULL,
  `iso_3166_3` VARCHAR(20) NULL,
  `population` INT NULL,
  `coordinates_ns` VARCHAR(10) NULL,
  `coordinates_ew` VARCHAR(10) NULL,
  `wgs_84_lat` DECIMAL(10,7) NULL,
  `wgs_84_lon` DECIMAL(10,7) NULL,
  `stock_code` VARCHAR(20) NULL,
  `linked_html` VARCHAR(1000) NULL,
  `linked_rdf` VARCHAR(1000) NULL,
  `linked_jpg` VARCHAR(1000) NULL,
  PRIMARY KEY (`cartridge`, `term_id`),
  INDEX `type_idx` (`type` ASC),
  INDEX `parent_idx` (`parent_term_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unstructured`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unstructured`.`categories` ;

CREATE TABLE IF NOT EXISTS `unstructured`.`categories` (
  `kb_id` VARCHAR(20) NOT NULL,
  `category_id` VARCHAR(20) NOT NULL,
  `parent_category_id` VARCHAR(20) NULL,
  `category` VARCHAR(100) NULL,
  PRIMARY KEY (`kb_id`, `category_id`),
  INDEX `category` (`category` ASC),
  INDEX `parent_idx` (`parent_category_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
